- name: Add nginx config
  sudo: yes
  template: src=logs.ryanbigg.com.j2 dest=/etc/nginx/sites-available/logs.ryanbigg.com mode=0644 owner=root group=root

- name: Link nginx config to sites-enabled
  file: state=link src=/etc/nginx/sites-available/logs.ryanbigg.com dest=/etc/nginx/sites-enabled/logs.ryanbigg.com
  sudo: yes

- name: Check nginx config
  command: nginx -t
  sudo: yes
  notify: restart nginx