- name: Add puma-manager
  template: src=puma-manager.j2 dest=/etc/init/puma-manager.conf force=yes mode=755
  tags: puma

- name: Add puma config
  template: src=etc_puma.conf.j2 dest=/etc/puma.conf force=yes mode=755
  tags: puma

- name: Add puma init script
  template: src=etc_init_puma.j2 dest=/etc/init/puma.conf force=yes mode=755
  tags: puma

- name: Add puma shared/config
  template: src=puma_production.j2 dest={{deploy_directory}}/shared/config/puma/production.rb force=yes mode=755
  tags: puma

- name: Make shared/tmp/sockets
  file: path={{deploy_directory}}/shared/tmp/sockets group=deploy owner=deploy state=directory
  tags: tmp

- name: restart puma-manager
  command: restart puma-manager  

- name: Install nginx
  apt: pkg=nginx state=latest

- name: Remove the default app
  command: rm -rf /etc/nginx/sites-enabled/default

- name: Remove the app's config, if exists
  command: rm -rf /etc/nginx/sites-enabled/default

- name: Remove the app's symlink, if exists
  command: rm -rf /etc/nginx/sites-enabled/{{app_name}}

- name: Configure nginx for the app
  template: src=etc_nginx_sites-available-template.conf.j2 dest=/etc/nginx/sites-available/{{app_name}} group=www-data owner=www-data force=yes

- name: Enable the app
  command: ln -s /etc/nginx/sites-available/{{app_name}} /etc/nginx/sites-enabled/{{app_name}}

- name: Restart nginx
  action: service name=nginx state=restarted

